apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-api
  namespace: rca
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - rca
    labelSelectors:
      app: api
