apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: rca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: rca-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: constants
            - name: DB_USER
              value: rca
            - name: DB_PASSWORD
              value: rca_password

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: rca
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
